### ISSUE TITLE
Readme.md is missing

### ISSUE THREAD

**Issue by SIL0RAK** [Knopkee/React_components#1]
Readme.md is missing from project.

Readme should include :
* project description
* instructions how to build project
* contribution rules

more info: https://www.makeareadme.com/

**Comment by Knopkee** [comment]
Ten nelabai ir projektu pavadinti galima. Ten paprasta uzduotis buvo, kad
pamatyti ar mokame su komponentais kazka sukurti. Tai mokytojai nuoroda
nusiusti reikejo. Man atrodo ji ir reikalavo tik tu triju failu. Plius dar
reikes ten koreguoti, nes is bootstrap komponentai naudojami, tai is class,
i className pakeisti reikes.

**Comment by SIL0RAK** [comment]
Still each repository should have instructions and description.
